[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/info"
  to = "/.netlify/functions/info"
  status = 200

[[redirects]]
  from = "/api/watch"
  to = "/.netlify/functions/watch"
  status = 200
